Repository Hanaro-FX/Hanaro-FX, pull requests merged in 2024-05, with the labels that each got.

#17 7 feature/user
  build.gradle
  src/main/java/com/hana/app/data/dto/UserDTO.java
  src/main/java/com/hana/app/repository/UserRepository.java
  src/main/java/com/hana/app/service/KakaoService.java
  src/main/java/com/hana/app/service/UserService.java
  src/main/java/com/hana/controller/user/UserController.java
  src/main/resources/application-dev.yml
  src/main/resources/mapper/usermapper.xml
  src/main/webapp/views/index.jsp
Labels: enhancement

#19 feat: datepicker 주말 선택 비활성화
  src/main/resources/static/css/portfolio/result.css
  src/main/webapp/views/portfolio/result.jsp
Labels: enhancement

#25 22 feature/utilize login info
  src/main/java/com/hana/controller/mypage/MypageController.java
  src/main/java/com/hana/controller/portfolio/PortfolioController.java
  src/main/webapp/views/portfolio/create.jsp
Labels: enhancement

#28 feat: 카카오톡 공유하기 구현
  src/main/resources/static/img/Hanaro-FX.png
  src/main/webapp/views/portfolio/result.jsp
Labels: enhancement

#30 24 feature/draw line graph
  src/main/java/com/hana/controller/portfolio/PortfolioController.java
  src/main/java/com/hana/controller/portfolio/PortfolioRestController.java
  src/main/resources/mapper/portfolioMapper.xml
  src/main/resources/static/css/portfolio/result.css
  src/main/webapp/views/index.jsp
  src/main/webapp/views/portfolio/create.jsp
  src/main/webapp/views/portfolio/result.jsp
Labels: enhancement

#37 36 feature/update portfolio result css
  src/main/resources/static/css/portfolio/result.css
  src/main/webapp/views/portfolio/result.jsp
Labels: enhancement

#42 39 refactor/exception
  src/main/java/com/hana/app/common/ErrorCode.java
  src/main/java/com/hana/app/common/response/ErrorResponse.java
  src/main/java/com/hana/app/exception/BusinessException.java
  src/main/java/com/hana/app/exception/GlobalExceptionHandler.java
  src/main/java/com/hana/app/service/KakaoService.java
  src/main/java/com/hana/controller/portfolio/PortfolioController.java
Labels: refactoring

#44 41 refactorresult
  src/main/java/com/hana/app/service/PortfolioService.java
  src/main/resources/static/js/datepicker.js
  src/main/resources/static/js/drawChart.js
  src/main/webapp/views/portfolio/result.jsp
Labels: refactoring

#45 Fix: Minus 7 days from data-collecting code from response
  src/main/java/com/hana/app/service/PortfolioService.java
Labels: bug

#46 31 feature/test
  build.gradle
  src/main/java/com/hana/app/service/PortfolioService.java
  src/test/java/com/hana/mypage/MyPageTests.java
  src/test/java/com/hana/portfolio/PortfolioTests.java
Labels: enhancement

#51 bug/assetSummation
  src/main/java/com/hana/app/service/PortfolioService.java
  src/main/webapp/views/portfolio/result.jsp
Labels: bug

#55 feat: 카카오 공유 페이지 수정
  src/main/java/com/hana/controller/portfolio/PortfolioController.java
  src/main/webapp/views/portfolio/result.jsp
Labels: enhancement
